### ISSUE TITLE
Can not install to a device

### ISSUE THREAD

**Issue by vualeks** [johnno1962/InjectionLite#2]
Hi,

I just tried it and it seems to be working ok, same as InjectionIII standalone app, with just one problem. It doesn't allow me install builds on a real device at all. I get the error 
`InjectionLite can only be used in the simulator or unsandboxed macOS`
which is fine, I don't want/expect it to inject to the device, just a regular install etc. Can it just ignore injecting if we install on real device without stopping the install completely?

**Comment by johnno1962** [comment]
Hmm, yes, perhaps I should change that to. a #warning when the smoke clears from your other issue.

**Comment by johnno1962** [comment]
I've pushed and tagged this change.
