### ISSUE TITLE
Cannot find type 'FileWatcher' in scope

### ISSUE THREAD

**Issue by vualeks** [johnno1962/InjectionLite#3]
I've just tried 1.1.4 version and it puts out a warning now regarding installation on a real device, but there are other issues
<img width="1433" alt="Screenshot 2023-03-11 at 16 28 30" src="https://user-images.githubusercontent.com/13743682/224493105-d8fd6002-aace-4c2d-b1ee-dd29a574eee6.png">

**Comment by johnno1962** [comment]
I've amended this now and added tag 1.1.5. Cn you see if this version runs with your particular classes and we can get back to the HotReloading problems. It may fail in the same way. What version of OS/Xcode is this?

**Comment by vualeks** [comment]
1.1.5 now builds and installs ok on real device. I'm using Xcode 14.2 (14C18) and Ventura 13.2.1

**Comment by johnno1962** [comment]
OK, Thanks for checking this.
